import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const khmerOSSiemreap = localFont({
  src: "./fonts/KhmerOSSiemreap.ttf",
  variable: "--font-khmerOSSiemreap",
  weight: "100 200 300 400 500 600 700 800 900",
});

// export const metadata: Metadata = {
//   title: "Royal Work App",
//   description: "Generated by CamCyber",
// };
// Update metadata with Open Graph and Twitter tags
export const metadata: Metadata = {
  title: "Royal Work App",
  description: "Generated by CamCyber",
  openGraph: {
    title: "Royal Work App",
    description: "Generated by CamCyber",
    url: "https://royal-work-web.vercel.app", // Replace with your actual URL
    images: [
      {
        url: "/images/CamCyber_Logo_Draft.png", // Path to your image in the public directory
        width: 1200,
        height: 630,
        alt: "Royal Work App",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image", // Twitter card type
    title: "Royal Work App",
    description: "Generated by CamCyber",
    images: ["/images/CamCyber_Logo_Draft.png"], // Path to your image in the public directory
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${khmerOSSiemreap.variable} antialiased`}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
