import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Footer from "@/components/Footer";

const khmerOSSiemreap = localFont({
  src: "./fonts/KhmerOSSiemreap.ttf",
  variable: "--font-khmerOSSiemreap",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Royal Work App",
  description: "Generated by ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${khmerOSSiemreap.variable} antialiased`}>
        <Header />
        <AntdRegistry>{children}</AntdRegistry>
        <Footer />
      </body>
    </html>
  );
}
