import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

// const khmerOSSiemreap = localFont({
//   src: "./fonts/KhmerOSSiemreap.ttf",
//   variable: "--font-khmerOSSiemreap",
//   weight: "100 200 300 400 500 600 700 800 900",
// });

const Kantumruy = localFont({
  src: "./fonts/KantumruyPro.ttf",
  variable: "--font-kantumruy",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Royal Work App",
  description: "Generated by CamCyber",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Kantumruy.variable} antialiased`}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
